server:
  port: 5000

telemetry:
  port: 4317
  host: localhost

kafka:
  client:
    clientId: catalog-backend
    brokers: localhost:29092
  consumer:
    groupId: catalog-consumer
    allowAutoTopicCreation: true

database:
  psql:
    # In case you want to use an URL instead
    # url: postgres://sa_catalog:sa_catalog_pwd@localhost:5433/catalog
    host: localhost
    port: 5433
    username: sa_catalog
    password: sa_catalog_pwd
    database: catalog
    debug: true
