name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  catalog:
    uses: polyflix/.github/.github/workflows/node-ci.yml@main
    with:
      package-migration: true
    secrets: inherit
